spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  h2:
    console:
      enabled: true

jwt:
  issuer: b1uesoda@naver.com
  secret-key: spring-boot