spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 421006170168-c4brh8njarvdg06kuprh9qrfd94f4nfk.apps.googleusercontent.com
            client-secret:
            scope:
              - email
              - profile

jwt:
  issuer: b1uesoda@naver.com
  secret-key: spring-boot